---
- hosts: all
  tasks:
    - name: install latest version of nginx
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started