---
- hosts: all
  tasks:
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: Tags from host {{ tags }}